variables:
  GOPATH: "$CI_PROJECT_DIR/.go"

cache:
  paths:
    - .go/pkg/mod

build:
  image: golang:1.11.5
  script:
    - make install

test:
  image: golang:1.11.5
  script:
    - GOFLAGS=-cover make test
  coverage: '\d+.\d+% of statements'
  artifacts:
    reports:
      junit: "TEST_*.xml"

lint:
  image: golang:1.11.5
  script:
    - make lint
